# Generated by Django 6.0.4 on 2026-04-09 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(default='weekly', max_length=50)),
                ('portfolio_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('returns_percent', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank', '-portfolio_value'],
                'unique_together': {('user', 'period_label')},
            },
        ),
    ]
