# Generated by Django 6.0.4 on 2026-04-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('prediction', models.CharField(max_length=30)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('source', models.CharField(default='mock-ml-engine', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
